---
# Default values for backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "uzubtsou"
  name: "backend"
  pullPolicy: "IfNotPresent"
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# Security token
token: "token"

# backend config
backend:
  command: ["yarn", "server:prod"]

# database
database:
  name: "coffee_dev" # default value, can be overridden
  username: "postgres" # replace with actual username
  password: "postgres" # replace with actual password
  host: "postgresql" # replace with actual host and port
  # port: ""  # default port 5432

job:
  schedule: "0 0 * * *"
  command: ["yarn", "jobs:supply:prod"]
  restartPolicy: "OnFailure"
  # successfulJobsHistoryLimit: 3
  # failedJobsHistoryLimit: 1
  # concurrencyPolicy: "Forbid"
  # startingDeadlineSeconds: 200
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi

imagePullSecrets: []

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 1Gi

serviceAccount:
  create: false

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
