---
# Source: backend/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: deployment
  template:
    metadata:
      labels:
        name: deployment
    spec:
      containers:
        - name: backend
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          image: uzubtsou/backend:0.0.1
          imagePullPolicy: IfNotPresent
          command:
            - yarn
            - server:dev
          env:
            - name: PORT
              value: "8080"
            - name: NODE_ENV
              value: development
            - name: API_KEY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: token
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: database_url
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 60
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
