---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  finalizers:
    - finalizers.fluxcd.io
  name: backend-dev
  namespace: develop
spec:
  interval: 1m0s
  path: ./infra/kubernetes/develop
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: develop
