apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../apps/backend

namespace: develop
namePrefix: dev-
nameSuffix: -backend

patches:
  - path: deployment-backend.yaml

generatorOptions:
  labels:
    app: deployment

secretGenerator:
  - name: database-config
    type: Opaque
    literals:
      - database_url="postgres://postgres:postgres@postgresql:5432/coffee_dev"
  - name: secrets
    type: Opaque
    literals:
      - token="token"
