---
# Source: backend/templates/database-config.yaml
apiVersion: v1
kind: Secret
metadata:
  name: database-config
type: Opaque
data:
  database_url: "postgres://postgres:postgres@postgresql:5432/coffee_dev"
---
# Source: backend/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  token: "token"
