apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.secrets" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ default "" .Values.token | b64enc | quote }}
