apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.databaseConfig" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
data:
  database_url: {{ include "backend.databaseURL" . | b64enc | quote }}